### ISSUE TITLE
显示错误

### ISSUE THREAD

**Issue by Val-istar-Guo** [arkmuntasser/css-triggers#2]
![image](https://cloud.githubusercontent.com/assets/12405937/23310963/4d7f9b06-faef-11e6-90d6-b7a46a72a41f.png)

background的前面的小圆点显示有错误。

**Comment by arkmuntasser** [comment]
@Val-istar-Guo Thank you for bringing this to my attention. I am unable to reproduce this. What other packages do you have installed? It might be a conflict with another package.

**Comment by Val-istar-Guo** [comment]
![image](https://cloud.githubusercontent.com/assets/12405937/23328528/02c7f2e2-fb5e-11e6-95bb-01ccda4d3110.png)
![image](https://cloud.githubusercontent.com/assets/12405937/23328529/0aa44c36-fb5e-11e6-9757-c4c1166fb3bb.png)
![image](https://cloud.githubusercontent.com/assets/12405937/23328531/12255cac-fb5e-11e6-8d1e-1b536261325b.png)
![image](https://cloud.githubusercontent.com/assets/12405937/23328534/1a1f1ce0-fb5e-11e6-8206-8581d7380cad.png)
![image](https://cloud.githubusercontent.com/assets/12405937/23328536/2bcc8c5c-fb5e-11e6-9b9d-d60c0b67c188.png)
![image](https://cloud.githubusercontent.com/assets/12405937/23328538/352daccc-fb5e-11e6-9407-ea0f79f8d803.png)
![image](https://cloud.githubusercontent.com/assets/12405937/23328541/4709cb24-fb5e-11e6-9912-cf80baf35299.png)
